version: '3'

services:

  prestashop:
    image: prestashop/prestashop:1.7-7.0
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: mysql
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - esgi-prestashop:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
     - 8181:80
    environment:
      PMA_HOST: mysql

volumes:
  esgi-prestashop: